### ISSUE TITLE
Fehlermeldung: offline

### ISSUE THREAD

**Issue by Dasch1** [Nico0302/SMG-Vertretungsplan#3]
![Screenshot_20200116-154844](https://user-images.githubusercontent.com/49644395/72535429-d17bbd80-3878-11ea-9ef1-c12e020cf38f.jpg)
^ Es wäre hilfreich, wenn genauer beschrieben würde, was falsch gelaufen ist. Die WLAN, sowie die Internetverbindung ist vorhanden. Wenn es nicht zu viel Arbeit ist, wäre es cool, wenn es genauer bestimmt wird.

**Comment by Nico0302** [comment]
Wurde in https://github.com/Nico0302/SMG-Vertretungsplan/commit/b6fd957369f5d106a5280aea05941eea18a36128 behoben. Die verschiedenen Fehlermeldungen werden nun direkt angezeigt.

**Comment by Nico0302** [comment]
Das Problem sollte damit im nächsten Release behoben sein.
